# Generated by Django 2.2.7 on 2019-12-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20191202_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
