# Generated by Django 2.2.7 on 2019-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_client_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_editor',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
